// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID          int     `json:"id"`
	ProductCode string  `json:"productCode"`
	ProductName string  `json:"productName"`
	Quantity    int     `json:"quantity"`
	Price       float64 `json:"price"`
	Promo       string  `json:"promo"`
}

type ItemInput struct {
	ProductCode string `json:"productCode"`
	Quantity    int    `json:"quantity"`
}

type Order struct {
	ID           int          `json:"id"`
	CustomerName string       `json:"customerName"`
	OrderAmount  float64      `json:"orderAmount"`
	Items        []*OrderItem `json:"items"`
}

type OrderInput struct {
	CustomerName string       `json:"customerName"`
	Items        []*ItemInput `json:"items"`
}
